name: Flutter CI

on:
  push:
    branches: [ ci_auto ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test casdoor-flutter-example  on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-11]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: "2.8.1"
      - name: Install dependencies
        run: flutter packages get
      - name: Analyze
        run: flutter analyze
      - name: Format
        run: flutter format --set-exit-if-changed .
      - name: Run tests
        run: flutter test --coverage
      - name: Upload coverage to Codecov
        if: startsWith(matrix.os, 'macos')
        uses: codecov/codecov-action@v1.0.6

  build-ios:
    name: Build casdoor-flutter-sdk iOS on ${{ matrix.os }} with Xcode ${{ matrix.xcode }} and Flutter ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12]
        xcode:
          ["12.5.1", "13.0", "13.3.1"]
        flutter:
          ["2.8.1"]
        exclude:
          - os: macos-11
            xcode: 13.3.1
          - os: macos-12
            xcode: 12.5.1
          - os: macos-12
            xcode: 13.0
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Xcode select
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: ${{ matrix.flutter }}
      - name: Flutter doctor (version check)
        run: flutter doctor
      - name: Build iOS
        run: flutter build ios --no-codesign
        env:
          OTHER_SWIFT_FLAGS: "-warnings-as-errors"
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  build-android:
    name: Build casdoor-flutter-sdk Android on ${{ matrix.os }} and Flutter ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        flutter:
          ["2.8.1"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # OpenJDK
          java-version: '11' # Specific (older) version needed for Gradle wrapper
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: ${{ matrix.flutter }}
      - name: Build Android
        run: flutter build appbundle

  build-macos:
    name: Build casdoor-flutter-sdk macOS on ${{ matrix.os }} with Xcode ${{ matrix.xcode }} and Flutter ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12]
        xcode:
          ["12.5.1", "13.0", "13.3.1"]
        flutter:
          ["2.8.1"]
        exclude:
          - os: macos-11
            xcode: 13.3.1
          - os: macos-12
            xcode: 12.5.1
          - os: macos-12
            xcode: 13.0
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Xcode select
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: ${{ matrix.flutter }}
      - name: Enable macOS Desktop Integration
        run: flutter config --enable-macos-desktop
      - name: Flutter doctor (version check)
        run: flutter doctor
      - name: Build macOS
        run: flutter build macos
        env:
          OTHER_SWIFT_FLAGS: "-warnings-as-errors"
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  build-web:
    name: Build casdoor-flutter-sdk Web on ${{ matrix.os }} and Flutter ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        flutter:
          ["2.8.1"]
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: ${{ matrix.flutter }}
      - name: Build Web
        run: flutter build web

  # release on Github and pub.dev
  publish:
    needs: test
    if: github.repository == 'ziliangyu/casdoor-flutter-example' && github.event_name == 'push'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install -g "@semantic-release/changelog"
      - run: npm install -g "@semantic-release/git"
      - run: npm install -g "pub-semantic-release"

      - name: Semantic Release
        run: |
          export NODE_PATH="$(npm root -g)"
          npx semantic-release@17
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN  }}